# Generated by Django 4.1.3 on 2022-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=8)),
                ('body', models.TextField()),
                ('material_type', models.CharField(choices=[('theory', 'Theoretic Materials'), ('practice', 'Practical Material')], default='theory', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='lessonentity',
            name='materials',
            field=models.ManyToManyField(related_name='lessons', to='lessons.materialentity'),
        ),
    ]
