# Generated by Django 4.1.3 on 2022-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_profileentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileentity',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profileentity',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
