# Generated by Django 4.1.3 on 2022-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_commententity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialentity',
            name='material_type',
            field=models.CharField(choices=[('theory', 'Theoretic Materials'), ('practice', 'Practical Material'), ('test', 'Testing Material')], default='theory', max_length=16),
        ),
    ]
